# -*- coding: utf-8 -*-
"""facmaskcustom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PAjwrzTm3R-hqhW1PFXazK-MsSYdSiyl
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="SLDIywqFskE8jMc06PsC")
project = rf.workspace("suman-gole").project("facemask-5tq1l")
dataset = project.version(2).download("yolov5")

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

import torch
from yolov5 import utils
display = utils.notebook_init()

!python train.py --img 640 --batch 2 --epochs 30 --data /content/facemask-2/data.yaml --weights yolov5s.pt --cache

!python detect.py --weights /content/yolov5/runs/train/exp2/weights/best.pt --img 640 --conf 0.25 --source /content/facemask.mp4

!python detect.py --weights /content/best.pt --img 640 --conf 0.25 --source /content/drive/MyDrive/chinesemask.mp4

!python detect.py --weights /content/best.pt  --source /content/nomaskface.mp4

